In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
cust_df = pd.read_csv('data/train.csv',encoding='latin-1')

In [5]:
cust_df.head()

,ID,var3,var15,imp_ent_var16_ult1,imp_op_var39_comer_ult1,imp_op_var39_comer_ult3,imp_op_var40_comer_ult1,imp_op_var40_comer_ult3,imp_op_var40_efect_ult1,imp_op_var40_efect_ult3,...,saldo_medio_var33_hace2,saldo_medio_var33_hace3,saldo_medio_var33_ult1,saldo_medio_var33_ult3,saldo_medio_var44_hace2,saldo_medio_var44_hace3,saldo_medio_var44_ult1,saldo_medio_var44_ult3,var38,TARGET
0,1,2,23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,39205.170000,0
1,3,2,34,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,49278.030000,0
2,4,2,23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,67333.770000,0
3,8,2,37,0.0,195.0,195.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,64007.970000,0
4,10,2,39,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,117310.979016,0

In [15]:
cust_df['TARGET'].value_counts()

0    73012
1     3008
Name: TARGET, dtype: int64

In [16]:
cust_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76020 entries, 0 to 76019
Columns: 371 entries, ID to TARGET
dtypes: float64(111), int64(260)
memory usage: 215.2 MB

In [17]:
cust_df.columns

Index(['ID', 'var3', 'var15', 'imp_ent_var16_ult1', 'imp_op_var39_comer_ult1',
       'imp_op_var39_comer_ult3', 'imp_op_var40_comer_ult1',
       'imp_op_var40_comer_ult3', 'imp_op_var40_efect_ult1',
       'imp_op_var40_efect_ult3',
       ...
       'saldo_medio_var33_hace2', 'saldo_medio_var33_hace3',
       'saldo_medio_var33_ult1', 'saldo_medio_var33_ult3',
       'saldo_medio_var44_hace2', 'saldo_medio_var44_hace3',
       'saldo_medio_var44_ult1', 'saldo_medio_var44_ult3', 'var38', 'TARGET'],
      dtype='object', length=371)

In [18]:
cust_df.describe()

,ID,var3,var15,imp_ent_var16_ult1,imp_op_var39_comer_ult1,imp_op_var39_comer_ult3,imp_op_var40_comer_ult1,imp_op_var40_comer_ult3,imp_op_var40_efect_ult1,imp_op_var40_efect_ult3,...,saldo_medio_var33_hace2,saldo_medio_var33_hace3,saldo_medio_var33_ult1,saldo_medio_var33_ult3,saldo_medio_var44_hace2,saldo_medio_var44_hace3,saldo_medio_var44_ult1,saldo_medio_var44_ult3,var38,TARGET
count,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,...,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,7.602000e+04,76020.000000
mean,75964.050723,-1523.199277,33.212865,86.208265,72.363067,119.529632,3.559130,6.472698,0.412946,0.567352,...,7.935824,1.365146,12.215580,8.784074,31.505324,1.858575,76.026165,56.614351,1.172358e+05,0.039569
std,43781.947379,39033.462364,12.956486,1614.757313,339.315831,546.266294,93.155749,153.737066,30.604864,36.513513,...,455.887218,113.959637,783.207399,538.439211,2013.125393,147.786584,4040.337842,2852.579397,1.826646e+05,0.194945
min,1.000000,-999999.000000,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.163750e+03,0.000000
25%,38104.750000,2.000000,23.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.787061e+04,0.000000
50%,76043.000000,2.000000,28.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.064092e+05,0.000000
75%,113748.750000,2.000000,40.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.187563e+05,0.000000
max,151838.000000,238.000000,105.000000,210000.000000,12888.030000,21024.810000,8237.820000,11073.570000,6600.000000,6600.000000,...,50003.880000,20385.720000,138831.630000,91778.730000,438329.220000,24650.010000,681462.900000,397884.300000,2.203474e+07,1.000000

In [24]:
cust_df.loc[cust_df['var3']==-999999,'var3'] = 2

In [28]:
cust_df = cust_df.drop(columns='ID')

In [29]:
cust_df

,var3,var15,imp_ent_var16_ult1,imp_op_var39_comer_ult1,imp_op_var39_comer_ult3,imp_op_var40_comer_ult1,imp_op_var40_comer_ult3,imp_op_var40_efect_ult1,imp_op_var40_efect_ult3,imp_op_var40_ult1,...,saldo_medio_var33_hace2,saldo_medio_var33_hace3,saldo_medio_var33_ult1,saldo_medio_var33_ult3,saldo_medio_var44_hace2,saldo_medio_var44_hace3,saldo_medio_var44_ult1,saldo_medio_var44_ult3,var38,TARGET
0,2,23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,39205.170000,0
1,2,34,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,49278.030000,0
2,2,23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,67333.770000,0
3,2,37,0.0,195.0,195.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,64007.970000,0
4,2,39,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,117310.979016,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76015,2,48,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,60926.490000,0
76016,2,39,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,118634.520000,0
76017,2,23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,74028.150000,0
76018,2,25,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,84278.160000,0
76019,2,46,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,117310.979016,0

In [36]:
x=cust_df[cust_df.columns.difference(["TARGET"])]

In [35]:
y=cust_df['TARGET']

In [37]:
from sklearn.model_selection import train_test_split

In [39]:
x_train, x_test, y_train, y_test = train_test_split(
x, y, test_size=0.2, random_state=42,stratify=y)

In [45]:
y_train.value_counts()/y_train.count()

0    0.960438
1    0.039562
Name: TARGET, dtype: float64

In [47]:
y_test.value_counts()/y_test.count()

0    0.960405
1    0.039595
Name: TARGET, dtype: float64

In [58]:
from xgboost import XGBClassifier
from sklearn.metrics import roc_auc_score
from sklearn.metrics import accuracy_score

In [53]:
xgb_model = XGBClassifier(n_estimators=400, random_state=42)

In [60]:
xgb_model.fit(x_train,y_train, early_stopping_rounds=100, eval_metric="auc",
             eval_set=[(x_train,y_train),(x_test,y_test)])

[0]	validation_0-auc:0.81985	validation_1-auc:0.81561
Multiple eval metrics have been passed: 'validation_1-auc' will be used for early stopping.

Will train until validation_1-auc hasn't improved in 100 rounds.
[1]	validation_0-auc:0.83381	validation_1-auc:0.82966
[2]	validation_0-auc:0.83949	validation_1-auc:0.82925
[3]	validation_0-auc:0.84622	validation_1-auc:0.83176
[4]	validation_0-auc:0.84712	validation_1-auc:0.83252
[5]	validation_0-auc:0.84969	validation_1-auc:0.83517
[6]	validation_0-auc:0.85380	validation_1-auc:0.83832
[7]	validation_0-auc:0.85777	validation_1-auc:0.83947
[8]	validation_0-auc:0.86154	validation_1-auc:0.84139
[9]	validation_0-auc:0.86419	validation_1-auc:0.84276
[10]	validation_0-auc:0.86691	validation_1-auc:0.84391
[11]	validation_0-auc:0.87004	validation_1-auc:0.84383
[12]	validation_0-auc:0.87326	validation_1-auc:0.84554
[13]	validation_0-auc:0.87576	validation_1-auc:0.84599
[14]	validation_0-auc:0.87767	validation_1-auc:0.84631
[15]	validation_0-auc:0.88019	validation_1-auc:0.84656
[16]	validation_0-auc:0.88233	validation_1-auc:0.84695
[17]	validation_0-auc:0.88360	validation_1-auc:0.84753
[18]	validation_0-auc:0.88562	validation_1-auc:0.84757
[19]	validation_0-auc:0.88613	validation_1-auc:0.84796
[20]	validation_0-auc:0.88701	validation_1-auc:0.84764
[21]	validation_0-auc:0.88970	validation_1-auc:0.84640
[22]	validation_0-auc:0.89107	validation_1-auc:0.84655
[23]	validation_0-auc:0.89134	validation_1-auc:0.84686
[24]	validation_0-auc:0.89221	validation_1-auc:0.84761
[25]	validation_0-auc:0.89231	validation_1-auc:0.84786
[26]	validation_0-auc:0.89296	validation_1-auc:0.84779
[27]	validation_0-auc:0.89361	validation_1-auc:0.84784
[28]	validation_0-auc:0.89497	validation_1-auc:0.84718
[29]	validation_0-auc:0.89543	validation_1-auc:0.84722
[30]	validation_0-auc:0.89596	validation_1-auc:0.84723
[31]	validation_0-auc:0.89614	validation_1-auc:0.84742
[32]	validation_0-auc:0.89682	validation_1-auc:0.84737
[33]	validation_0-auc:0.89768	validation_1-auc:0.84705
[34]	validation_0-auc:0.89814	validation_1-auc:0.84737
[35]	validation_0-auc:0.90053	validation_1-auc:0.84661
[36]	validation_0-auc:0.90221	validation_1-auc:0.84665
[37]	validation_0-auc:0.90288	validation_1-auc:0.84686
[38]	validation_0-auc:0.90343	validation_1-auc:0.84717
[39]	validation_0-auc:0.90371	validation_1-auc:0.84711
[40]	validation_0-auc:0.90390	validation_1-auc:0.84679
[41]	validation_0-auc:0.90483	validation_1-auc:0.84653
[42]	validation_0-auc:0.90532	validation_1-auc:0.84622
[43]	validation_0-auc:0.90560	validation_1-auc:0.84577
[44]	validation_0-auc:0.90606	validation_1-auc:0.84581
[45]	validation_0-auc:0.90753	validation_1-auc:0.84565
[46]	validation_0-auc:0.90940	validation_1-auc:0.84506
[47]	validation_0-auc:0.91081	validation_1-auc:0.84484
[48]	validation_0-auc:0.91158	validation_1-auc:0.84463
[49]	validation_0-auc:0.91173	validation_1-auc:0.84467
[50]	validation_0-auc:0.91198	validation_1-auc:0.84473
[51]	validation_0-auc:0.91208	validation_1-auc:0.84479
[52]	validation_0-auc:0.91222	validation_1-auc:0.84484
[53]	validation_0-auc:0.91248	validation_1-auc:0.84475
[54]	validation_0-auc:0.91330	validation_1-auc:0.84449
[55]	validation_0-auc:0.91349	validation_1-auc:0.84452
[56]	validation_0-auc:0.91388	validation_1-auc:0.84484
[57]	validation_0-auc:0.91401	validation_1-auc:0.84472
[58]	validation_0-auc:0.91407	validation_1-auc:0.84480
[59]	validation_0-auc:0.91568	validation_1-auc:0.84512
[60]	validation_0-auc:0.91711	validation_1-auc:0.84445
[61]	validation_0-auc:0.91735	validation_1-auc:0.84438
[62]	validation_0-auc:0.91749	validation_1-auc:0.84431
[63]	validation_0-auc:0.91799	validation_1-auc:0.84466
[64]	validation_0-auc:0.91816	validation_1-auc:0.84458
[65]	validation_0-auc:0.91892	validation_1-auc:0.84399
[66]	validation_0-auc:0.91908	validation_1-auc:0.84372
[67]	validation_0-auc:0.91916	validation_1-auc:0.84384
[68]	validation_0-auc:0.91928	validation_1-auc:0.84331
[69]	validation_0-auc:0.91999	validation_1-auc:0.84279
[70]	validation_0-auc:0.92074	validation_1-auc:0.84287
[71]	validation_0-auc:0.92188	validation_1-auc:0.84235
[72]	validation_0-auc:0.92256	validation_1-auc:0.84172
[73]	validation_0-auc:0.92302	validation_1-auc:0.84172
[74]	validation_0-auc:0.92389	validation_1-auc:0.84185
[75]	validation_0-auc:0.92438	validation_1-auc:0.84148
[76]	validation_0-auc:0.92465	validation_1-auc:0.84139
[77]	validation_0-auc:0.92533	validation_1-auc:0.84155
[78]	validation_0-auc:0.92561	validation_1-auc:0.84112
[79]	validation_0-auc:0.92631	validation_1-auc:0.84053
[80]	validation_0-auc:0.92659	validation_1-auc:0.84046
[81]	validation_0-auc:0.92743	validation_1-auc:0.84029
[82]	validation_0-auc:0.92837	validation_1-auc:0.84068
[83]	validation_0-auc:0.92871	validation_1-auc:0.84042
[84]	validation_0-auc:0.92902	validation_1-auc:0.84004
[85]	validation_0-auc:0.92916	validation_1-auc:0.84006
[86]	validation_0-auc:0.92923	validation_1-auc:0.84000
[87]	validation_0-auc:0.92933	validation_1-auc:0.83967
[88]	validation_0-auc:0.92954	validation_1-auc:0.83959
[89]	validation_0-auc:0.92975	validation_1-auc:0.83959
[90]	validation_0-auc:0.92995	validation_1-auc:0.83964
[91]	validation_0-auc:0.93012	validation_1-auc:0.83999
[92]	validation_0-auc:0.93015	validation_1-auc:0.83999
[93]	validation_0-auc:0.93119	validation_1-auc:0.83954
[94]	validation_0-auc:0.93200	validation_1-auc:0.83917
[95]	validation_0-auc:0.93229	validation_1-auc:0.83947
[96]	validation_0-auc:0.93281	validation_1-auc:0.83885
[97]	validation_0-auc:0.93338	validation_1-auc:0.83915
[98]	validation_0-auc:0.93356	validation_1-auc:0.83910
[99]	validation_0-auc:0.93360	validation_1-auc:0.83877
[100]	validation_0-auc:0.93370	validation_1-auc:0.83889
[101]	validation_0-auc:0.93421	validation_1-auc:0.83857
[102]	validation_0-auc:0.93470	validation_1-auc:0.83815
[103]	validation_0-auc:0.93607	validation_1-auc:0.83771
[104]	validation_0-auc:0.93659	validation_1-auc:0.83728
[105]	validation_0-auc:0.93664	validation_1-auc:0.83732
[106]	validation_0-auc:0.93669	validation_1-auc:0.83739
[107]	validation_0-auc:0.93728	validation_1-auc:0.83756
[108]	validation_0-auc:0.93786	validation_1-auc:0.83715
[109]	validation_0-auc:0.93801	validation_1-auc:0.83712
[110]	validation_0-auc:0.93839	validation_1-auc:0.83731
[111]	validation_0-auc:0.93846	validation_1-auc:0.83723
[112]	validation_0-auc:0.93908	validation_1-auc:0.83755
[113]	validation_0-auc:0.93930	validation_1-auc:0.83730
[114]	validation_0-auc:0.93939	validation_1-auc:0.83730
[115]	validation_0-auc:0.93943	validation_1-auc:0.83722
[116]	validation_0-auc:0.93946	validation_1-auc:0.83724
[117]	validation_0-auc:0.93964	validation_1-auc:0.83694
[118]	validation_0-auc:0.93972	validation_1-auc:0.83692
[119]	validation_0-auc:0.93987	validation_1-auc:0.83649
Stopping. Best iteration:
[19]	validation_0-auc:0.88613	validation_1-auc:0.84796

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=400, n_jobs=0, num_parallel_tree=1, random_state=42,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [61]:
y_pred = xgb_model.predict(x_test)

In [62]:
accuracy_score(y_test,y_pred)

0.9601420678768745

In [63]:
y_pred_proba = xgb_model.predict_proba(x_test)

In [70]:
roc_auc_score(y_test,y_pred_proba[:,1],average='macro')

0.8479600027484517

In [67]:
y_pred_proba

array([[0.98864156, 0.01135844],
       [0.9628031 , 0.0371969 ],
       [0.9959354 , 0.00406463],
       ...,
       [0.9844829 , 0.01551714],
       [0.983839  , 0.01616101],
       [0.9675754 , 0.03242465]], dtype=float32)